### 全件取得
Get http://localhost:8080/stock-info

### 全件取得(Active)
Get http://localhost:8080/stock-info/active

### 検索(カテゴリ名・名前・個数)
GET http://localhost:8080/stock-info/category/プロペラ/name/サイレントウィンド/amount/500/than/以上 

### 検索(カテゴリ名・名前)
GET http://localhost:8080/stock-info/category/プロペラ/name/サイレントウィンド

### 検索(カテゴリ名・個数)
GET http://localhost:8080/stock-info/category/プロペラ/amount/10/than/以上

### 検索(名前・個数)
GET http://localhost:8080/stock-info/name/サイレントウィンド/amount/500/than/以上 

### 検索(カテゴリ名)
GET http://localhost:8080/stock-info/category/プロペラ

### 検索(名前)
GET http://localhost:8080/stock-info/name/サイレントウィンド 

### 検索(個数)
GET http://localhost:8080/stock-info/amount/500/than/以上 






